kind: StatefulSet
apiVersion: apps/v1
metadata:
  name: mycluster-amq-broker-ss
spec:
  template:
    spec:
      containers:
        - name: mycluster-amq-broker-container
          env:
            - name: BROKER_XML
              valueFrom:
                configMapKeyRef:
                  name: broker-config
                  key: broker.xml
