# AMQ Broker Operator

## Missing broker.xml configuration

NOTE: Contains only the one used by the customer with different value from default.

* max-disk-usage -> maxDiskUsage
** Default value: 90
** Customer value: 96
* page-sync-timeout -> pageSyncTimeout
** Default value: with NIO is journal-buffer-timeout: 463999 footnote:[https://activemq.apache.org/components/artemis/documentation/latest/paging.html] 
** Customer value: 463999
* User Management (expected on 7.8):
** https://issues.redhat.com/browse/ENTMQBR-3387 
** https://issues.redhat.com/browse/ENTMQBR-3607
* Certificate Management (expected on 7.8):
** https://issues.redhat.com/browse/ENTMQBR-3401
** Currently you need to create all the secrets in advance.
* Bridge
* Divert


## Helm AMQ Broker Operator Integration.

. Install Operator to specific namespace on the cluster
.. This can be provided by the cluster-admin as namespaced installation and should give the right role to manage the AMQ Broker CRD.
+
NOTE: You cannot create more than one broker deployment in a given OpenShift project by deploying multiple broker Custom Resource (CR) instances. However, when you have created a broker deployment in a project, you can deploy multiple CR instances for addresses. https://access.redhat.com/documentation/en-us/red_hat_amq/7.7/html-single/deploying_amq_broker_on_openshift/index#con-br-operator-deployment-notes_broker-ocp[Reference].
. [pre-install hook] Restore AMQ Broker Operator
. [install/upgrade] Create kind: ActiveMQArtemis
. [install/upgrade] Deploy custom broker xml. 3 ways:
.. Set BROKER_XML environment variable with your custom broker.xml.
.. Mount ConfigMap resources hosting any custom configuration file.
.. Use S2I procedure with more customization requirements. footnote:[ActiveMQArtemis allows you to override the amq broker images]
. [post-install hook] Shutdown the AMQ Broker Operator
. [post-install hook] Adopt the AMQ Broker resource to Helm:
+
[source,yaml]
------
annotations:
  meta.helm.sh/release-name: release-name
  meta.helm.sh/release-namespace: namespace-name
labels:
  app.kubernetes.io/managed-by: Helm
------
. [post install] Adjust AMQ Broker Stateful set to use the custom broker xml.
. [test] Verify the installation is correct.


NOTE: A pre-hook install image requires oc client `quay.io/openshift/origin-cli:4.6` and running with edit role on the specific namespace.

## To Verify

. How scale down controller actives without the operator.
. Address creation, probably we are able to reuse it. `<address-setting match="None">`
. NetworkPolicy between two brokers.
