# AMQ Broker Operator Helm Enhancement

The aim is to automate the creation of the AMQ Broker Custom Resources and at the same time enhance the broker.xml with a configuration that is not yet available in the operator.
The helm chart keeps in sync the custom resources and the custom broker.xml.

## Prerequisites

. AMQ Broker Operator must running in your target namespace.

## Install AMQ Broker Helm Charts

`helm upgrade --install mycluster amq-broker/`

## Test it

`helm test mycluster`

## Custom Certificate Authority

`mkdir -p tls/{ca,broker}`

### Certificate Autority

This section is to simulate a private certificate authority.

. Certificate Authority (CA)
+
[source,bash]
-------
openssl req -new -newkey rsa:2048 -x509 -keyout tls/ca/ca.key -out tls/ca/ca.crt -days 365 -subj "/CN=mycompany.com"
-------

. Create a Truststore
+
[source,bash]
-------
    keytool -import -storepass password -file tls/ca/ca.crt -alias mycompany.com -keystore tls/ca/client.ts
-------

### Broker Certificate

. Broker Key
+
[source,bash]
-------
keytool -genkeypair -storepass password -keyalg RSA -keysize 2048 -dname "CN=mycluster-amq-broker-*-svc-rte-dxc.apps-crc.testing" -ext san="dns:mycluster-amq-broker-all-0-svc-rte-dxc.apps-crc.testing,dns:mycluster-amq-broker-all-0-svc.dxc.svc" -alias broker -keystore tls/broker/broker.ks
-------

. Certificate Signing Request (CSR)
+
[source,bash]
-------
keytool -certreq -storepass password -keyalg rsa -alias broker -keystore tls/broker/broker.ks -file tls/broker/tls.csr
-------

. Certificate Authority Sign
+
[source,bash]
-------
openssl x509 -req -CA tls/ca/ca.crt -CAkey tls/ca/ca.key -in tls/broker/tls.csr -out tls/broker/tls.crt -days 365 -CAcreateserial
    
keytool -import -v -trustcacerts -alias root -file tls/ca/ca.crt -keystore tls/broker/broker.ks
keytool -import -v -trustcacerts -alias broker -file tls/broker/tls.crt -keystore tls/broker/broker.ks
-------

.. Verify the chain
+
[source,bash]
-------
keytool -list -v -keystore tls/broker/broker.ks
-------

. Import to truststore
+
[source,bash]
-------
keytool -import -storepass password -file tls/broker/tls.crt -alias server -keystore tls/ca/client.ts
-------

### Create Secret

NOTE: Naming convention: `<CustomResourceName>-<AcceptorName>-secret`

[source,bash]
-------
oc create secret generic mycluster-amq-broker-all-secret \
  --from-file=tls/broker \
  --from-file=tls/ca/client.ts \
  --from-file=tls/ca/ca.crt \
  --from-literal=keyStorePassword=password \
  --from-literal=trustStorePassword=password
-------

IMPORTANT: Adopt with Helm

[source,bash]
-------
oc annotate secret/mycluster-amq-broker-all-secret meta.helm.sh/release-name=mycluster --overwrite 
oc annotate secret/mycluster-amq-broker-all-secret meta.helm.sh/release-namespace=dxc --overwrite 
oc label secret/mycluster-amq-broker-all-secret app.kubernetes.io/managed-by=Helm --overwrite
-------

### Install with Custom Certificate

`helm upgrade --install mycluster --set pki.self=false`


## Test External Client

. Extract Client TrustStore
+
`oc extract secret/mycluster-amq-broker-all-secret --keys=client.ts`

. Extract AMQ Endpoint

`export AMQ_ENDPOINT=$(oc get route mycluster-amq-broker-all-0-svc-rte --no-headers -o custom-columns=:.spec.host)`

. Launch Artemis Producer Command
+
[source,bash]
-------
./artemis producer --user amq --password amq --message-count 10 --url="tcp://${AMQ_ENDPOINT}:443?sslEnabled=true;trustStorePath=./client.ts;trustStorePassword=password"
Connection brokerURL = tcp://mycluster-amq-broker-all-0-svc-rte-dxc.apps-crc.testing:443?sslEnabled=true;trustStorePath=./client.ts;trustStorePassword=password
Producer ActiveMQQueue[TEST], thread=0 Started to calculate elapsed time ...

Producer ActiveMQQueue[TEST], thread=0 Produced: 10 messages
Producer ActiveMQQueue[TEST], thread=0 Elapsed time in second : 0 s
Producer ActiveMQQueue[TEST], thread=0 Elapsed time in milli second : 79 milli seconds
-------

. Launch Artemis Consumer Command
+
[source,bash]
-------
./artemis consumer --user amq --password amq --message-count 10 --url="tcp://${AMQ_ENDPOINT}:443?sslEnabled=true;trustStorePath=./client.ts;trustStorePassword=password"
Connection brokerURL = tcp://mycluster-amq-broker-all-0-svc-rte-dxc.apps-crc.testing:443?sslEnabled=true;trustStorePath=./client.ts;trustStorePassword=password
Consumer:: filter = null
Consumer ActiveMQQueue[TEST], thread=0 wait until 10 messages are consumed
Consumer ActiveMQQueue[TEST], thread=0 Consumed: 10 messages
Consumer ActiveMQQueue[TEST], thread=0 Elapsed time in second : 0 s
Consumer ActiveMQQueue[TEST], thread=0 Elapsed time in milli second : 17 milli seconds
Consumer ActiveMQQueue[TEST], thread=0 Consumed: 10 messages
Consumer ActiveMQQueue[TEST], thread=0 Consumer thread finished
-------

## Uninstall it

`helm uninstall mycluster --no-hooks`

## Progress

.Progress
[cols="5,3",options=header]
|===
|Task
|Status

| Add Address CRD logic
| DONE

| Patch AMQ Broker with custom dynamic configuration
| DONE

| Test Internal Connection Implementation
| DONE

| SSL Selfsigned Implementation
| DONE

| Test with External Client Implementation
| DONE

| Keystore and Truststore Password
| DONE

| SSL Custom CA Implementation, NOTE: if you create the certificate early it should work
| https://github.com/openlab-red/amq-broker-operator-helm/issues/2[#2]

| User Management
| https://github.com/openlab-red/amq-broker-operator-helm/issues/3[#3]

| Bridge and Diverts Implementation
| https://github.com/openlab-red/amq-broker-operator-helm/issues/1[#1]

| Network Policy
| https://github.com/openlab-red/amq-broker-operator-helm/issues/4[#4]

| Make sure that the operator creates all the Addresses
| TODO

| High Availability and How scale down controller actives without the operator.
| TODO

| Migrate one standalone broker
| TODO
|===

## Pseudo Code

. Install Operator to specific namespace on the cluster
.. This can be provided by the cluster-admin as namespaced installation and should give the right role to manage the AMQ Broker CRD.
+
NOTE: You cannot create more than one broker deployment in a given OpenShift project by deploying multiple broker Custom Resource (CR) instances. However, when you have created a broker deployment in a project, you can deploy multiple CR instances for addresses. https://access.redhat.com/documentation/en-us/red_hat_amq/7.7/html-single/deploying_amq_broker_on_openshift/index#con-br-operator-deployment-notes_broker-ocp[Reference].
. [pre-install hook] Restore AMQ Broker Operator
. [install/upgrade] Create kind: ActiveMQArtemis and ActiveMQArtemisAddress
. [install/upgrade] Create Config Map with custom broker xml.
. [post-install hook] Shutdown the AMQ Broker Operator
. [post-install hook] Adoptthe AMQ Broker resource to Helm:
+
[source,yaml]
------
annotations:
  meta.helm.sh/release-name: release-name
  meta.helm.sh/release-namespace: namespace-name
labels:
  app.kubernetes.io/managed-by: Helm
------
. [post install] Adjust AMQ Broker Stateful set to use the custom broker xml.
.. Set BROKER_XML environment variable with your custom broker.xml.
. [test] Verify the installation is correct.

NOTE: A *-hook install image requires oc client `quay.io/openshift/origin-cli:4.6` and running with edit role on the specific namespace.

## Important

* In AMQ Broker 7.7, if you want to configure any of the following items, you must add the appropriate configuration to the main CR instance before deploying the CR for the first time.
** Address settings
** The size of the Persistent Volume Claim (PVC) required by each broker in a deployment for persistent storage
** Limits and requests for memory and CPU for each broker in a deployment
* During an active scaling event, any further changes that you apply are queued by the Operator and executed only when scaling is complete. For example, suppose that you scale the size of your deployment down from four brokers to one. Then, while scaledown is taking place, you also change the values of the broker administrator user name and password. In this case, the Operator queues the user name and password changes until the deployment is running with one active broker.
* All CR changes – apart from changing the size of your deployment, or changing the value of the expose attribute for acceptors, connectors, or the console – cause existing brokers to be restarted. If you have multiple brokers in your deployment, only one broker restarts at a time.
* To configure address and queue settings for broker deployments on OpenShift Container Platform, you add configuration to an addressSettings section of the main Custom Resource (CR) instance for the broker deployment. This contrasts with standalone deployments on Linux or Windows, for which you add configuration to an address-settings element in the broker.xml configuration file.
* The format used for the names of configuration items differs between OpenShift Container Platform and standalone broker deployments. For OpenShift Container Platform deployments, configuration item names are in camel case, for example, defaultQueueRoutingType. By contrast, configuration item names for standalone deployments are in lower case and use a dash (-) separator, for example, default-queue-routing-type.
* Addresses are created by the AMQ Broker Operator using Artemis Jolokia and MBean.

## Reference

* https://access.redhat.com/documentation/en-us/red_hat_amq/7.7/html-single/deploying_amq_broker_on_openshift/index#con-br-configuring-broker-certificate-for-hostname-verification_broker-ocp

