apiVersion: broker.amq.io/v2alpha3
kind: ActiveMQArtemis
metadata:
  name: {{ include "amq-broker.fullname" . }}
  labels:
    {{- include "amq-broker.labels" . | nindent 4 }}
spec:
  acceptors:
    {{- toYaml .Values.acceptors | nindent 4 }}
  addressSettings:
    {{- toYaml .Values.addressSettings | nindent 4 }}
  adminPassword: {{ .Values.adminPassword }}
  adminUser: {{ .Values.adminUser }}
  console:
    {{- toYaml .Values.console | nindent 4 }}
  deploymentPlan:
    image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
    journalType: nio
    messageMigration: true
    persistenceEnabled: true
    requireLogin: false
    size: {{ .Values.replicaCount }}
  upgrades:
    enabled: false
