{{- range .Values.addresses }}
{{- $address := . -}}
{{- with $ }}
apiVersion: broker.amq.io/v2alpha2
kind: ActiveMQArtemisAddress
metadata:
  name: {{ $address.addressName }}
  labels:
  {{- include "amq-broker.labels" . | nindent 4 }}
spec:
  addressName: {{ $address.addressName }}
  queueName: {{ $address.queueName }}
  routingType: {{ $address.routingType }}
{{ end }}
{{- end }}

