apiVersion: broker.amq.io/v2alpha3
kind: ActiveMQArtemis
metadata:
  name: {{ include "amq-broker.fullname" . }}
  labels:
    {{- include "amq-broker.labels" . | nindent 4 }}
spec:
  acceptors:
  - name: all
    protocols: all
    port: 61617
    sslEnabled: false
  addressSettings:
    addressSetting:
      - addressFullPolicy: PAGE
        autoCreateDeadLetterResources: true
        autoCreateExpiryResources: true
        deadLetterQueueSuffix: .eq
        expiryQueueSuffix: .eq
        maxSizeBytes: '52428800'
        redeliveryDelay: 1000
        match: '#'
  adminPassword: amq
  adminUser: amq
  console:
    expose: true
    sslEnabled: false
  deploymentPlan:
    image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
    journalType: nio
    messageMigration: true
    persistenceEnabled: true
    requireLogin: false
    size: 1
  upgrades:
    enabled: false
