apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "amq-broker.fullname" . }}-post
  labels:
    {{- include "amq-broker.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
    "helm.sh/hook-weight": "0"
spec:
  backoffLimit: 2
  ttlSecondsAfterFinished: 100
  template:
    metadata:
      name: "{{ .Release.Name }}"
      labels:
        {{- include "amq-broker.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "amq-broker.serviceAccountName" . }}
      restartPolicy: Never
      containers:
      - name: post-install
        image: "quay.io/openshift/origin-cli:4.6"
        command:
        - /bin/bash
        - '-c'
        - |
            #!/bin/bash

            export AMQ_BROKER={{ include "amq-broker.fullname" . }}-ss

            # Wait the rollout of AMQ Broker Statefulset
            oc rollout status sts/$AMQ_BROKER -w
            
            # Scale Down the Operator
            oc scale --replicas=0 deployments/amq-broker-operator

            # Adopt Statefulset Broker
            oc annotate sts/$AMQ_BROKER meta.helm.sh/release-name={{ .Release.Name }} --overwrite 
            oc annotate sts/$AMQ_BROKER meta.helm.sh/release-namespace={{ .Release.Namespace }} --overwrite 
            oc label sts/$AMQ_BROKER app.kubernetes.io/managed-by=Helm --overwrite

            # Patch
            oc patch sts $AMQ_BROKER -p "$(</opt/config/patch.yaml)"
        volumeMounts:
        - name: kustomize
          mountPath: /opt/config
      volumes:
      - name: kustomize
        configMap:
          name: {{ include "amq-broker.fullname" . }}

            


