{{- range .Values.acceptors }}
{{- $acceptor := . -}}
{{- with $ }}
apiVersion: v1
kind: Secret
type: kubernetes.io/tls
metadata:
  name: {{ include "amq-broker.fullname" . }}-{{ $acceptor.name }}-secret
  labels:
  {{- include "amq-broker.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": "pre-install"
    "helm.sh/hook-delete-policy": "before-hook-creation"
data:
{{ ( include "amq-broker.gen-certs" . ) | indent 2 }}
{{- end }}
{{- end }}